Changed docs for manifest multi lang
socialhubio/socialhub-dev pull request #26
Opened 2021-11-15 13:55 UTC by nenadb97

2021-11-25 12:47 UTC, mikhalev-im requested changes
There is also a [swagger](https://github.com/socialhubio/socialhub-dev/blob/master/swagger.yaml) file in this repo that you need to adjust.

And please add a new entry to the [changelog](https://github.com/socialhubio/socialhub-dev/blob/master/docs/changelog.md).

2021-11-25 12:47 UTC, mikhalev-im commented on docs/general/manifest-api.md
> +| `label`         | Configuration of human readable title of the option which will be shown to the user as button label. |
Sound a bit confusing, can we maybe change it to something more simple:

`Button labels for different locales. Locale is selected depending on user settings.`

2021-11-25 12:47 UTC, mikhalev-im commented on docs/general/manifest-api.md
> +| `en`            | Human readable title of the option which will be shown to the user as button label in English. |
Lets not mix `title` / `label` and `option` / `button` in one sentence

I guess something like this should be enough:
`Human-readable label for English locale.`

2021-11-25 12:47 UTC, mikhalev-im commented on docs/general/manifest-api.md
> +| `de`            | Human readable title of the option which will be shown to the user as button label in German language. |
`Human-readable label for German locale.`

2021-11-25 12:47 UTC, mikhalev-im commented on docs/general/manifest-api.md
> +| `en`            | Human readable title of the option which will be shown to the user as button label in English. |
Please adjust similar to above

2021-11-25 12:47 UTC, mikhalev-im commented on docs/general/manifest-api.md
> +| `label`         | Configuration of human readable title of the option which will be shown to the user as button label. |
Please adjust similar to above

2021-11-25 12:47 UTC, mikhalev-im commented on docs/general/manifest-api.md
> +| `en`            | Human readable title of the option which will be shown to the user as button label in English. |
Please adjust similar to above

2021-11-26 05:04 UTC, mikhalev-im commented on docs/changelog.md
> +The following changes to the API are scheduled to be deployed in **calendar week 49**.
Please keep the spacing consistent, for example, add an empty line after headers (`##` and `###`)

2021-11-26 05:06 UTC, mikhalev-im commented on docs/changelog.md
> +`label: {
Maybe multiline code block fits better here (```js)

```js
label: {
    en: 'Reply',
    de: 'Antworten'
}
```

2021-11-30 14:19 UTC, schlagbauer approved these changes
Adjusted some smaller things but it is ready to be merged now

2021-12-14 08:39 UTC, merged